# -*- coding: utf-8 -*-

# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Imbigjetplane by Lamdzhihihih

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import Qt
import res
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1132, 800)
        Form.setWindowFlags(Qt.Qt.FramelessWindowHint)
        Form.setAttribute(Qt.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1100, 780))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(29, 10, 611, 711))
        self.label.setStyleSheet("border-image: url(:/img/40420.jpg);\n"
"border-top-left-radius:50px;\n"
"border-bottom-left-radius:50px;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(560, 10, 431, 711))
        self.label_2.setStyleSheet("QLabel#label_2{background-color:rgb(255, 255, 255);\n"
"border-top-right-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.hi = QtWidgets.QLabel(self.widget)
        self.hi.setGeometry(QtCore.QRect(670, 90, 200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(50)
        font.setBold(True)
        self.hi.setFont(font)
        self.hi.setObjectName("hi")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(850, 210, 50, 50))
        self.label_3.setStyleSheet("border-image: url(:/img/car-insurance.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(620, 330, 270, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82,101, 201);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(620, 440, 270, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{background-color:rgb(125, 145, 255);\n"
"border-radius:10px;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{background-color:rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:2px;\n"
"padding-top:2px;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(600, 230, 230, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(620, 550, 270, 80))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(60, 60))
        self.label_5.setMaximumSize(QtCore.QSize(60, 60))
        self.label_5.setStyleSheet("border-image: url(:/img/facebook.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setMinimumSize(QtCore.QSize(50, 50))
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setStyleSheet("border-image: url(:/img/gmail.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setMinimumSize(QtCore.QSize(50, 50))
        self.label_8.setMaximumSize(QtCore.QSize(50, 50))
        self.label_8.setStyleSheet("border-image: url(:/img/instagram.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setMinimumSize(QtCore.QSize(50, 50))
        self.label_6.setMaximumSize(QtCore.QSize(50, 50))
        self.label_6.setStyleSheet("border-image: url(:/img/tik-tok.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(660, 630, 200, 70))
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 20, 21, 24))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid white;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:2px;\n"
"padding-top:2px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(890, 20, 21, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid white;\n"
"}\n"
"\n"
"QPushButton#pushButton_5:pressed{\n"
"padding-left:2px;\n"
"padding-top:2px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.hi.setText(_translate("Form", "Hi!"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter Your Business Name"))
        self.pushButton.setText(_translate("Form", "Continue"))
        self.label_4.setText(_translate("Form", "Vehicle Protection Tools"))
        self.label_9.setText(_translate("Form", "Copyright 2023 Team 8 ltd "))
        self.pushButton_2.setText(_translate("Form", "X"))
        self.pushButton_5.setText(_translate("Form", "–"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
